<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="EasyModbusTCP" Version="5.6.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
		<PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
		<PackageReference Include="System.IO.Ports" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CompressionForce.Data\CompressionForce.Data.csproj" />
		<ProjectReference Include="..\CompressionForce.Domain\CompressionForce.Domain.csproj" />
		<ProjectReference Include="..\CompressionForce.Integrations\CompressionForce.Integrations.csproj" />
		<ProjectReference Include="..\CompressionForce.Services\CompressionForce.Services.csproj" />
	</ItemGroup>

</Project>
