// <auto-generated />
using System;
using CompressionForce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompressionForce.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoTareStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("MotorStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("MotorTrip")
                        .HasColumnType("boolean");

                    b.Property<int>("Revolutions")
                        .HasColumnType("integer");

                    b.Property<decimal>("S1Eject")
                        .HasColumnType("numeric");

                    b.Property<decimal>("S1Main")
                        .HasColumnType("numeric");

                    b.Property<decimal>("S1Pre")
                        .HasColumnType("numeric");

                    b.Property<decimal>("S2Eject")
                        .HasColumnType("numeric");

                    b.Property<decimal>("S2Main")
                        .HasColumnType("numeric");

                    b.Property<decimal>("S2Pre")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("last_updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("auto_tare_status", "public");
                });

            modelBuilder.Entity("CompressionForce.Data.Entities.LoadCellCalibrationRuntimeEntity", b =>
                {
                    b.Property<string>("LoadCellName")
                        .HasColumnType("text");

                    b.Property<decimal>("Factor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Offset")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LoadCellName");

                    b.ToTable("LoadCellCalibrationRuntimeEntity");
                });

            modelBuilder.Entity("CompressionForce.Data.Entities.LookupValueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LookupValues");
                });

            modelBuilder.Entity("CompressionForce.Data.Entities.PlcStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsLocalDbConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_local_db_connected");

                    b.Property<bool>("IsPlcConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_plc_connected");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<DateTime>("PlcHeartbeat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plc_heartbeat");

                    b.Property<string>("PlcIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plc_ip");

                    b.HasKey("Id");

                    b.ToTable("plc_status", "public");
                });

            modelBuilder.Entity("CompressionForce.Data.Entities.RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CompressionForce.Data.Entities.RecipeHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewParameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OldParameters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecipeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RecipeHistories");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.AlarmLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AlarmCreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlarmDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlarmLogs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Activity");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EventDescription");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .HasColumnType("text");

                    b.Property<string>("BatchCondition")
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<string>("BatchQty")
                        .HasColumnType("text");

                    b.Property<string>("BatchSize")
                        .HasColumnType("text");

                    b.Property<string>("BatchStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoodQty")
                        .HasColumnType("text");

                    b.Property<string>("LeftQty")
                        .HasColumnType("text");

                    b.Property<string>("ProdusedQty")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("RejectionQty")
                        .HasColumnType("text");

                    b.Property<string>("S2GoodQty")
                        .HasColumnType("text");

                    b.Property<string>("S2RejectionQty")
                        .HasColumnType("text");

                    b.Property<string>("TabletQty")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.BatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .HasColumnType("text");

                    b.Property<long?>("BatchSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EReventType")
                        .HasColumnType("text");

                    b.Property<string>("RecipeCode")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BatchHistories");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.CurrentBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwcLower")
                        .HasColumnType("text");

                    b.Property<string>("AwcUpper")
                        .HasColumnType("text");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejLower")
                        .HasColumnType("text");

                    b.Property<string>("RejUpper")
                        .HasColumnType("text");

                    b.Property<string>("S1AwcLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1AwcSetLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1AwcUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1FeederRatio")
                        .HasColumnType("text");

                    b.Property<string>("S1FillCam")
                        .HasColumnType("text");

                    b.Property<string>("S1FillDepth")
                        .HasColumnType("text");

                    b.Property<string>("S1MainPenetration")
                        .HasColumnType("text");

                    b.Property<string>("S1MainThickness")
                        .HasColumnType("text");

                    b.Property<string>("S1PrePenetration")
                        .HasColumnType("text");

                    b.Property<string>("S1PreThickness")
                        .HasColumnType("text");

                    b.Property<string>("S1RejLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S1RejUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2AwcLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2AwcSetLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2AwcUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2FeederRatio")
                        .HasColumnType("text");

                    b.Property<string>("S2FillCam")
                        .HasColumnType("text");

                    b.Property<string>("S2FillDepth")
                        .HasColumnType("text");

                    b.Property<string>("S2MainPenetration")
                        .HasColumnType("text");

                    b.Property<string>("S2MainThickness")
                        .HasColumnType("text");

                    b.Property<string>("S2PrePenetration")
                        .HasColumnType("text");

                    b.Property<string>("S2PreThickness")
                        .HasColumnType("text");

                    b.Property<string>("S2RejLowerLimit")
                        .HasColumnType("text");

                    b.Property<string>("S2RejUpperLimit")
                        .HasColumnType("text");

                    b.Property<string>("TurretRpm")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CurrentBatches");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.GroupPrivilege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("PrivilegeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupPrivileges");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.Privilage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Alarms")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AuditTrail")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AwcParameter")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Backup")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Batch")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Calibration")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Diagnostics")
                        .HasColumnType("boolean");

                    b.Property<string>("GroupLevel")
                        .HasColumnType("text");

                    b.Property<bool?>("Operation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Recipe")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Reports")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Security")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SignalMonitor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Privilages");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.PrivilageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Alarms")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Backup")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Batch")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Calibration")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Diagnostics")
                        .HasColumnType("boolean");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("GroupLevel")
                        .HasColumnType("text");

                    b.Property<bool?>("Operation")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Recipe")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Reports")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Security")
                        .HasColumnType("boolean");

                    b.Property<bool?>("SignalMonitor")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PrivilageHistories");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultEjectLoadS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultEjectLoadS1Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultEjectLoadS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultEjectLoadS2Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultMainLoadS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultMainLoadS1Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultMainLoadS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultMainLoadS2Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultMainSrelS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageS1")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FeederSpeedS1")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValueS1")
                        .HasColumnType("double precision");

                    b.Property<double?>("TabletQtyS1")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ResultMainSrelS1Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultMainSrelS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageS2")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("FeederSpeedS2")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValueS2")
                        .HasColumnType("double precision");

                    b.Property<double?>("TabletQtyS2")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ResultMainSrelS2Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultPreLoadS1B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultPreLoadS1Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ResultPreLoadS2B", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AverageLoad")
                        .HasColumnType("double precision");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P1")
                        .HasColumnType("double precision");

                    b.Property<double?>("P10")
                        .HasColumnType("double precision");

                    b.Property<double?>("P11")
                        .HasColumnType("double precision");

                    b.Property<double?>("P12")
                        .HasColumnType("double precision");

                    b.Property<double?>("P13")
                        .HasColumnType("double precision");

                    b.Property<double?>("P14")
                        .HasColumnType("double precision");

                    b.Property<double?>("P15")
                        .HasColumnType("double precision");

                    b.Property<double?>("P16")
                        .HasColumnType("double precision");

                    b.Property<double?>("P17")
                        .HasColumnType("double precision");

                    b.Property<double?>("P18")
                        .HasColumnType("double precision");

                    b.Property<double?>("P19")
                        .HasColumnType("double precision");

                    b.Property<double?>("P2")
                        .HasColumnType("double precision");

                    b.Property<double?>("P20")
                        .HasColumnType("double precision");

                    b.Property<double?>("P21")
                        .HasColumnType("double precision");

                    b.Property<double?>("P22")
                        .HasColumnType("double precision");

                    b.Property<double?>("P23")
                        .HasColumnType("double precision");

                    b.Property<double?>("P24")
                        .HasColumnType("double precision");

                    b.Property<double?>("P25")
                        .HasColumnType("double precision");

                    b.Property<double?>("P26")
                        .HasColumnType("double precision");

                    b.Property<double?>("P27")
                        .HasColumnType("double precision");

                    b.Property<double?>("P28")
                        .HasColumnType("double precision");

                    b.Property<double?>("P29")
                        .HasColumnType("double precision");

                    b.Property<double?>("P3")
                        .HasColumnType("double precision");

                    b.Property<double?>("P30")
                        .HasColumnType("double precision");

                    b.Property<double?>("P31")
                        .HasColumnType("double precision");

                    b.Property<double?>("P32")
                        .HasColumnType("double precision");

                    b.Property<double?>("P33")
                        .HasColumnType("double precision");

                    b.Property<double?>("P34")
                        .HasColumnType("double precision");

                    b.Property<double?>("P35")
                        .HasColumnType("double precision");

                    b.Property<double?>("P36")
                        .HasColumnType("double precision");

                    b.Property<double?>("P37")
                        .HasColumnType("double precision");

                    b.Property<double?>("P38")
                        .HasColumnType("double precision");

                    b.Property<double?>("P39")
                        .HasColumnType("double precision");

                    b.Property<double?>("P4")
                        .HasColumnType("double precision");

                    b.Property<double?>("P40")
                        .HasColumnType("double precision");

                    b.Property<double?>("P41")
                        .HasColumnType("double precision");

                    b.Property<double?>("P42")
                        .HasColumnType("double precision");

                    b.Property<double?>("P43")
                        .HasColumnType("double precision");

                    b.Property<double?>("P44")
                        .HasColumnType("double precision");

                    b.Property<double?>("P45")
                        .HasColumnType("double precision");

                    b.Property<double?>("P46")
                        .HasColumnType("double precision");

                    b.Property<double?>("P47")
                        .HasColumnType("double precision");

                    b.Property<double?>("P48")
                        .HasColumnType("double precision");

                    b.Property<double?>("P49")
                        .HasColumnType("double precision");

                    b.Property<double?>("P5")
                        .HasColumnType("double precision");

                    b.Property<double?>("P50")
                        .HasColumnType("double precision");

                    b.Property<double?>("P51")
                        .HasColumnType("double precision");

                    b.Property<double?>("P52")
                        .HasColumnType("double precision");

                    b.Property<double?>("P53")
                        .HasColumnType("double precision");

                    b.Property<double?>("P54")
                        .HasColumnType("double precision");

                    b.Property<double?>("P55")
                        .HasColumnType("double precision");

                    b.Property<double?>("P56")
                        .HasColumnType("double precision");

                    b.Property<double?>("P57")
                        .HasColumnType("double precision");

                    b.Property<double?>("P58")
                        .HasColumnType("double precision");

                    b.Property<double?>("P59")
                        .HasColumnType("double precision");

                    b.Property<double?>("P6")
                        .HasColumnType("double precision");

                    b.Property<double?>("P60")
                        .HasColumnType("double precision");

                    b.Property<double?>("P61")
                        .HasColumnType("double precision");

                    b.Property<double?>("P62")
                        .HasColumnType("double precision");

                    b.Property<double?>("P63")
                        .HasColumnType("double precision");

                    b.Property<double?>("P64")
                        .HasColumnType("double precision");

                    b.Property<double?>("P65")
                        .HasColumnType("double precision");

                    b.Property<double?>("P7")
                        .HasColumnType("double precision");

                    b.Property<double?>("P8")
                        .HasColumnType("double precision");

                    b.Property<double?>("P9")
                        .HasColumnType("double precision");

                    b.Property<string>("RecipeName")
                        .HasColumnType("text");

                    b.Property<long?>("Revolution")
                        .HasColumnType("bigint");

                    b.Property<double?>("S1FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("S2FeederSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("SrelValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("TurretSpeed")
                        .HasColumnType("double precision");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResultPreLoadS2Bs");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.SecuritySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWrongAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("PasswordExpiryDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SecuritySettings");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.ServoCalibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("JogSpeed")
                        .HasColumnType("numeric");

                    b.Property<string>("ServoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SetPosition")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SetSpeed")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TorqueLimit")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ServoCalibrations");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ERdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ERlevel")
                        .HasColumnType("text");

                    b.Property<string>("ERname")
                        .HasColumnType("text");

                    b.Property<bool?>("UserStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.UserLoginHistroy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ERdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EReventType")
                        .HasColumnType("text");

                    b.Property<string>("ERlevel")
                        .HasColumnType("text");

                    b.Property<string>("ERname")
                        .HasColumnType("text");

                    b.Property<bool?>("UserStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserLoginHistroys");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.UserManagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ERemail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERlevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ERpassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserManagements");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.UserManagementHistroy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ERdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EReventType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ERexpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ERid")
                        .HasColumnType("integer");

                    b.Property<string>("ERlevel")
                        .HasColumnType("text");

                    b.Property<string>("ERname")
                        .HasColumnType("text");

                    b.Property<string>("ERpassword")
                        .HasColumnType("text");

                    b.Property<bool?>("UserStatus")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("UserManagementHistroys");
                });

            modelBuilder.Entity("CompressionForce.Domain.Entities.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationLogout")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NoOfWrongAttempt")
                        .HasColumnType("integer");

                    b.Property<int?>("PasswordExpiryDate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
